### ISSUE TITLE
error when the only available markdown data is an empty link

### ISSUE THREAD

**Issue by ammaratef45** [ammaratef45/flutter_markdown_editor#13]
when the user inserts [](https://...) it throws an exception

A solution to the problem in flutter_markdown is proposed in flutter/flutter_markdown#295

Use a temporary solution now then upgrade to the version of flutter_markdown that solves the problem and remove the temporary solution

**Comment by Abhijeet-sonkar** [comment]
Can I work on this issue?

**Comment by ammaratef45** [comment]
@Abhijeet-sonkar Sure, it's all yours

**Comment by ammaratef45** [comment]
@Abhijeet-sonkar The solution proposed has been merged, now you just need to update the version of `flutter_markdown ` in the pubspec file, can you do that?

**Comment by Abhijeet-sonkar** [comment]
@ammaratef45  Yeah sure I will do this

**Comment by ammaratef45** [comment]
@Abhijeet-sonkar thanks for contributing
